kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    "global":
      "resolve_timeout": "5m"
    "receivers":
      - name: 'alertmanager-bot'
        webhook_configs:
        - url: 'http://alertmanager-bot:8080'
          send_resolved: true
    "route":
      "group_by":
      - "job"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "alertmanager-bot"
      "repeat_interval": "12h"
      "routes":
        - receiver: alertmanager-bot
          match:
            alertname: Watchdog