---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector: 
    app: grafana
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      protocol: TCP