apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
      prometheus.ioscrape: 'true'
      prometheus.ioport:   '9090'
  
spec:
  selector: 
    app: prometheus-server
  #type: NodePort  
  ports:
    - port: 9090
      #targetPort: 9090 
      #nodePort: 31000
      #- port: 9090