apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.14.0
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
          - name: NODE_OPTIONS
            value: --max-old-space-size=1024
          - name: SERVER_BASEPATH
            value: "/kibana"
          - name: SERVER_REWRITEBASEPATH
            value: "true"
        resources:
          limits:
            memory: 800Mi
          requests:
            cpu: 400m
            memory: 512Mi
        ports:
        - containerPort: 5601