apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: myapp
    name: myapp
spec:
    replicas: 2
    selector:
        matchLabels:
            app: myapp
    template:
        metadata:
            labels:
                app: myapp
        spec:
            containers:
              - image: ghcr.io/$IMAGE_NAME:$IMAGE_VERSION
                imagePullPolicy: Always
                name: myapp
                envFrom:
                  - secretRef:
                      name: app-secret
                  - configMapRef:
                      name: app-config
                ports:
                  - containerPort: 5000
                    name: myapp
            imagePullSecrets:
              - name: githreg
