apiVersion: v1
data:
  auth: ZXBhbTokYXByMSRVNTFHNThDcCRnSUtpRGFrQ1l5dU8wb3ptbldmbzQvCg==
kind: Secret
metadata:
  name: basic-auth
  namespace: monitoring
type: Opaque
---
apiVersion: v1
data:
  auth: ZXBhbTokYXByMSRVNTFHNThDcCRnSUtpRGFrQ1l5dU8wb3ptbldmbzQvCg==
kind: Secret
metadata:
  name: basic-auth-def
  namespace: default
type: Opaque